### ISSUE TITLE
Followup to #14

### ISSUE THREAD

**Issue by voxik** [chef/libyajl2-gem#15]
If you told me "there is Rake task which copies the files from 'vendor' directory to the 'ext' directory as part of release process", everything could be clear. You lock the thread instead, not very helpful :(

**Comment by coderanger** [comment]
@voxik yajl is buried like a million levels deep in our dependency system and we've all been up to our eyeballs in build issues, and you started with a very combative tone. None of us have any bandwidth to fix things that are as firmly not broken as our JSON handling. If you've got some broader concern then maybe ask us in Slack but if your goal is packaging Chef in accordance with Fedora policy we'll all just say "nope not interested".

**Comment by voxik** [comment]
NP, dealing with Fedora policies is my thing, I just need some support from time to time. And apologies for the tone. I did not want to offend anybody.

**Comment by lamont-granquist** [comment]
You used the word "rubbish" which is very pejorative.  And its clear that you don't understand why these gems are set up the way they are, and why they're actually designed to be hostile to vendor policies.  We fought with trying to vendor chef the "distro way" in Ubuntu and that approach basically failed years ago and we suggest now that everyone install our omnibus packages which install into /opt/chef and /opt/chefdk and those installs are consistent across all the Unix distros that we support from Fedora/Ubuntu to AIX/Solaris/RHEL5/SuSE/FreeBSD.  Unless you have AIX and Solaris boxes that you can test changes to these packages, the amount of time that I would have to personally burn to test everything you produce to make sure it didn't break something crazy that we have to support probably exceeds the utility of trying to get package to play nicely with the Fedora distro (which, again, we tell all our users just to install our omnibus packages into /opt/chef, which they're all mostly happy with and we have a distinct lack of paying customers demanding that the packages get into core Fedora repos).  Even in the Fedora world we have a hard requirement to continue to support RHEL5 (and ruby 1.8.5 was buggy to begin with and hasn't been supported in ages and we MUST have our ruby 2.4.1 install on RHEL5 in order to support it -- we have no time to deal with segfaults from 10 year old ruby language versions -- and the fact that we ship a modern ruby 2.4.1 to distros like RHEL5 pull along a pile of other libraries -- and then we eat the cost of supporting security updates on those libs because its 100x easier than supporting the ancient distro versions).
